import type { Metadata } from "next";

import { ConvexClientProvider } from "@/providers/convex-auth";
import { cn } from "@/lib/utils";

import { Inter, Geist_Mono, Figtree } from "next/font/google";
import "@/styles/globals.css";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-figtree" });
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("antialiased font-sans", geistMono.variable, inter.variable, figtree.variable)}>
      <body>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
